### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by vipint99** [networklore/ansible-cisco-snmp#7]
Hi Patrick,
I am first time using this module. Getting this error:

Unable to import cisco_snmp_portsecurity due to invalid syntax

installed nelsnmp 
cloned ansible-cisco-snmp  
ansible.cfg - pointing library to ansible-cisco-snmp/library

------------------
$ cat ansible.cfg

[defaults]

library = /tmp/certs/ansible-cisco-snmp/librar

running following code: 

cat  test-snmp.yml
```
---
 - hosts: all
   connection: local
   gather_facts: no
    
   tasks:
           #    - name: test 
           # cisco_snmp_interface: 
           #host={{ inventory_hostname }}
           #version=2c 
           #community=private
        - cisco_snmp_portsecurity: host={{ inventory_hostname }} version=v3 community=private interface_name=FastEthernet0/2 portsecurity=enabled max=5

```
Error:
```
PLAYBOOK: test_snmp.yml ********************************************************
1 plays in test_snmp.yml

PLAY [all] *********************************************************************
META: ran handlers

TASK [cisco_snmp_portsecurity] *************************************************
task path: /tmp/certs/test_snmp.yml:12
fatal: [wayzataoclab729-swt.XXXX.com]: FAILED! => {"msg": "Unable to import cisco_snmp_portsecurity due to invalid syntax"}

Same Syntax error came when I tried to use interface module

```
